# Example configuration file
# Copy this file to config.toml and replace the values with your own.

[backend]
DATABASE_URL = "postgresql://USER:PASSWORD@localhost:5432/DATABASE_NAME"
SECRET_KEY = "your-secret-key"
ALLOWED_ORIGINS = "http://localhost:5173"
RESEND_API_KEY="your-resend-api-key"
RESEND_FROM_EMAIL="onboarding@resend.dev"

[frontend]
VITE_API_URL = "http://localhost:5173/api"
VITE_APP_NAME = "YourAppName"

# Docker-specific overrides
[backend.docker]
DATABASE_URL = "postgresql://USER:PASSWORD@host.docker.internal:5432/DATABASE_NAME"
SECRET_KEY = "your-secret-key"
ALLOWED_ORIGINS = "http://localhost"
RESEND_API_KEY="your-resend-api-key"
RESEND_FROM_EMAIL="onboarding@resend.dev"

[frontend.docker]
VITE_API_URL = "http://localhost/api"
VITE_APP_NAME = "YourAppName"