services:

  nginx:
    build: './nginx'
    container_name: wilvault-nginx
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend

  backend:
    build: ./backend
    container_name: wilvault-backend
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_URL=${VITE_API_URL}
    env_file:
      - ./frontend/.env