services:

  nginx:
    build: './nginx'
    container_name: wilvault-nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - frontend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf 
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt

  backend:
    build: ./backend
    container_name: wilvault-backend
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_URL=${VITE_API_URL}
    container_name: wilvault-frontend
    env_file:
      - ./frontend/.env
